name = "Generic USB Controller"
deadzone = 0.18

[[axes]]
name = "left_x"
index = 0
label = "Left Stick X"

[[axes]]
name = "left_y"
index = 1
label = "Left Stick Y"

[[axes]]
name = "right_x"
index = 2
label = "Right Stick X"

[[axes]]
name = "right_y"
index = 3
label = "Right Stick Y"

[[buttons]]
name = "a"
index = 0
label = "Face South (A)"

[[buttons]]
name = "b"
index = 1
label = "Face East (B)"

[[buttons]]
name = "x"
index = 2
label = "Face West (X)"

[[buttons]]
name = "y"
index = 3
label = "Face North (Y)"

[[buttons]]
name = "lb"
index = 4
label = "Left Bumper"

[[buttons]]
name = "rb"
index = 5
label = "Right Bumper"

[[buttons]]
name = "select"
index = 6
label = "Select / Back"

[[buttons]]
name = "start"
index = 7
label = "Start"

[[buttons]]
name = "l_stick"
index = 8
label = "Left Stick Button"

[[buttons]]
name = "r_stick"
index = 9
label = "Right Stick Button"

[[hats]]
name = "dpad"
index = 0
label = "D-Pad"
